### ISSUE TITLE
[New feature] Manage command configuration 

### ISSUE THREAD

**Issue by bhou** [criteo/command-launcher#119]
Add a new type of command launcher managed resource: "config". Each command can request to such configurations in  `requestedResources` property.

A package should also declare the list of configurations it requires so that the command launcher can provide a proper interface to access them. 

Example manifest:
```yaml
pkgName: demo-pkg
version: 1.0.0
cmds:
  - name: test-cmd
     type: executable
     requiredResources: [ 'CONFIG_NAME_1', 'CONFIG_NAME_2' ]

configs:
  - name: NAME_1
    type: string
    default: hello
  - name: NAME_2
     type: integer
     default: 10
```
