### ISSUE TITLE
Manifest.mf - Add a section for specifying command env variables

### ISSUE THREAD

**Issue by zeralight** [criteo/command-launcher#143]
Currently the way to pass env variables:

```yaml
cmds:
  - name: pretty-grep
    type: executable
    executable: bash
    args:
      - -c
      - export GREP_OPTIONS="--color=auto -r --exclude-dir=node_modules --exclude-dir=.git" grep

```

But we can have a cleaner syntax if we can specify environment variables in a dedicated attribute:
```yaml
cmds:
  - name: pretty-grep
     type: executable
     executable: grep
     env:
       - GREP_OPTIONS: --color=auto -r --exclude-dir=node_modules --exclude-dir=.git

```

**Comment by jdevera** [comment]
I came here to open an issue about this and I've been experimenting a bit with a change about it.

My proposed syntax would be to use yaml mappings instead of lists so it would look like:

```yaml
cmds:
  - name: pretty-grep
    type: executable
    executable: grep
    env:
      GREP_OPTIONS: --color=auto -r --exclude-dir=node_modules --exclude-dir=.git
      ANOTHER_VAR: value
```

In my particular use case, I need to **add** something to an env var that already exists (like the PATH variable). So I thought I would propose the change in two stages:

## Step 1: Support env vars in Manifest.mf

Loading all environment variables in `.Env` so one can do `.Env.ENV_VAR`:

```json
"cmds": [
  {
    "name": "conditional-env",
    "type": "executable",
    "executable": "{{.PackageDir}}/bin/app",
    "args": ["--env", "{{if .Env.NODE_ENV}}{{.Env.NODE_ENV}}{{else}}development{{end}}"]
  }
]
```

## Step 2: Support passing environment variables to executables

```yaml
cmds:
  - name: my_python_program
    type: executable
    executable: "{{.PackageDir}}/program.py"
    env:
      PYTHONPATH: "{{.PackageDir}}/lib:{{.Env.PYTHONPATH}}"
```


Those two steps can also come in any order.

I have the first one almost ready for a PR, but @bhou-crto if you see this before I push the PR, it would be great to hear what you think.
