### ISSUE TITLE
Add login hook to enable custom login procedure

### ISSUE THREAD

**Issue by bhou-crto** [criteo/command-launcher#66]
The built-in "login" command today stores the user name and password into the system vault, and pass `[APP NAME]_USERNAME` and `[APP NAME]_PASSWORD` environment variable to the execution command on runtime. 

For enterprise usage, usually, SSO is enabled. To access different services, command passes a token, instead of the user name and password. We should provide a "login" hook in the manifest to get and store such token and pass it through an env var (ex. [APP_NAME]_LOGIN_TOKEN) to the execution command.

This hook can be provided as a command in a normal package, but hidden from the command launcher interface. 

Propose new type in cmd manifest: `extension`, and an additional field to indicate when this command will be triggered `extension`

```
pkgName: test-pkg
version: 1.0.0
cmds:
  - name: login-hook
    type: extension
    extension: login
    executable: "{{.Root}}/bin/login-hook"
    args: [ ... ]
```
