### ISSUE TITLE
Enable user consent to access the local resources/credentials

### ISSUE THREAD

**Issue by bhou-crto** [criteo/command-launcher#67]
In the manifest file, command should declare their intention to access the execution context provided by command launcher at runtime. This is particular important when accessing sensitive information like credentials.

During the command execution time, command launcher should request user consent to allow these command access such information. 

Ex. the "test-cmd" requests to access the "LOGIN_TOKEN" and "USERNAME" context.
```
pkgName: test-pkg
version: 1.0.0
cmds:
  - name: test-cmd
    type: executable
    executable: "{{.Root}}/bin/exec.sh"
    context: [ "LOGIN_TOKEN", "USERNAME" ]
```

Example consent message:
```
$ cl test-cmd
test-cmd requests to access following context:
- LOGIN_TOKEN
- USERNAME
Allow access? y/N
```

The user consent should be stored to avoid requesting consent each time.
